### ISSUE TITLE
Missing custom css of the project

### ISSUE THREAD

**Issue by pihomeserver** [Wtower/generator-makrina#34]
In the admin.ejs, there is no include of the generated file in build/css/\<project name\>.css (same folder than style.min.css). And should be included in the latest to override default styles

**Comment by Wtower** [comment]
Hello and thank you for your contributed issues. The generated file is included in:

https://github.com/Wtower/generator-makrina/blob/master/generators/app/templates/views/admin.ejs#L9

**Comment by pihomeserver** [comment]
Strange as in my case, the sass file of the project called \<project name\>.sass is well compiled but not included within the style.min.css so i had to update the admin.ejs file
